# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dxf2gcode_pyQt4_ui.ui'
#
# Created: Wed Jan 04 22:56:14 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1146, 848)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mytabWidget = QtGui.QTabWidget(self.centralwidget)
        self.mytabWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.mytabWidget.setObjectName(_fromUtf8("mytabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tableView_2 = QtGui.QTableView(self.tab)
        self.tableView_2.setObjectName(_fromUtf8("tableView_2"))
        self.verticalLayout_4.addWidget(self.tableView_2)
        self.treeView_2 = QtGui.QTreeView(self.tab)
        self.treeView_2.setObjectName(_fromUtf8("treeView_2"))
        self.verticalLayout_4.addWidget(self.treeView_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.mytabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Linie 1 Edit Feld", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtGui.QLineEdit(self.tab_2)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Linie 2 Edit Feld", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_3)
        self.lineEdit_4 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_4)
        self.lineEdit_5 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_5)
        self.treeView = QtGui.QTreeView(self.tab_2)
        self.treeView.setMinimumSize(QtCore.QSize(0, 250))
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.treeView)
        self.tableView = QtGui.QTableView(self.tab_2)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.SpanningRole, self.tableView)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.mytabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.mytabWidget)
        self.MyGraphicsView = MyGraphicsView(self.centralwidget)
        self.MyGraphicsView.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.MyGraphicsView.setToolTip(QtGui.QApplication.translate("MainWindow", "Graphic Area for drawing\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.MyGraphicsView.setObjectName(_fromUtf8("MyGraphicsView"))
        self.horizontalLayout.addWidget(self.MyGraphicsView)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.myMessageBox = myMessageBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.myMessageBox.sizePolicy().hasHeightForWidth())
        self.myMessageBox.setSizePolicy(sizePolicy)
        self.myMessageBox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.myMessageBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.myMessageBox.setObjectName(_fromUtf8("myMessageBox"))
        self.verticalLayout.addWidget(self.myMessageBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1146, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuExport = QtGui.QMenu(self.menubar)
        self.menuExport.setEnabled(True)
        self.menuExport.setStatusTip(QtGui.QApplication.translate("MainWindow", "Export the current project to G-Code", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExport.setTitle(QtGui.QApplication.translate("MainWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExport.setObjectName(_fromUtf8("menuExport"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuTolerances = QtGui.QMenu(self.menubar)
        self.menuTolerances.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTolerances.setObjectName(_fromUtf8("menuTolerances"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_File = QtGui.QAction(MainWindow)
        self.actionLoad_File.setText(QtGui.QApplication.translate("MainWindow", "Load File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_File.setStatusTip(QtGui.QApplication.translate("MainWindow", "Load DXF or other supportet document", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_File.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_File.setObjectName(_fromUtf8("actionLoad_File"))
        self.actionExit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon)
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setStatusTip(QtGui.QApplication.translate("MainWindow", "Exit DXF2GCODE and close window", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionShow_WP_Zero = QtGui.QAction(MainWindow)
        self.actionShow_WP_Zero.setCheckable(True)
        self.actionShow_WP_Zero.setChecked(True)
        self.actionShow_WP_Zero.setEnabled(False)
        self.actionShow_WP_Zero.setText(QtGui.QApplication.translate("MainWindow", "Show WP zero", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_WP_Zero.setObjectName(_fromUtf8("actionShow_WP_Zero"))
        self.actionShow_path_directions = QtGui.QAction(MainWindow)
        self.actionShow_path_directions.setCheckable(True)
        self.actionShow_path_directions.setChecked(False)
        self.actionShow_path_directions.setEnabled(False)
        self.actionShow_path_directions.setText(QtGui.QApplication.translate("MainWindow", "Show path directions", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_path_directions.setObjectName(_fromUtf8("actionShow_path_directions"))
        self.actionShow_disabled_paths = QtGui.QAction(MainWindow)
        self.actionShow_disabled_paths.setCheckable(True)
        self.actionShow_disabled_paths.setChecked(False)
        self.actionShow_disabled_paths.setEnabled(False)
        self.actionShow_disabled_paths.setText(QtGui.QApplication.translate("MainWindow", "Show disabled paths", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_disabled_paths.setObjectName(_fromUtf8("actionShow_disabled_paths"))
        self.actionAutoscale = QtGui.QAction(MainWindow)
        self.actionAutoscale.setEnabled(False)
        self.actionAutoscale.setText(QtGui.QApplication.translate("MainWindow", "Autoscale", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoscale.setObjectName(_fromUtf8("actionAutoscale"))
        self.actionDelete_G0_paths = QtGui.QAction(MainWindow)
        self.actionDelete_G0_paths.setEnabled(False)
        self.actionDelete_G0_paths.setText(QtGui.QApplication.translate("MainWindow", "Delete G0 paths", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_G0_paths.setObjectName(_fromUtf8("actionDelete_G0_paths"))
        self.actionTolerances = QtGui.QAction(MainWindow)
        self.actionTolerances.setText(QtGui.QApplication.translate("MainWindow", "Tolerances", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTolerances.setObjectName(_fromUtf8("actionTolerances"))
        self.actionScale_all = QtGui.QAction(MainWindow)
        self.actionScale_all.setEnabled(False)
        self.actionScale_all.setText(QtGui.QApplication.translate("MainWindow", "Scale all", None, QtGui.QApplication.UnicodeUTF8))
        self.actionScale_all.setObjectName(_fromUtf8("actionScale_all"))
        self.actionRotate_all = QtGui.QAction(MainWindow)
        self.actionRotate_all.setEnabled(False)
        self.actionRotate_all.setText(QtGui.QApplication.translate("MainWindow", "Rotate all", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRotate_all.setObjectName(_fromUtf8("actionRotate_all"))
        self.actionMove_WP_zero = QtGui.QAction(MainWindow)
        self.actionMove_WP_zero.setEnabled(False)
        self.actionMove_WP_zero.setText(QtGui.QApplication.translate("MainWindow", "Move WP zero", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMove_WP_zero.setObjectName(_fromUtf8("actionMove_WP_zero"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionOptimize_Shape = QtGui.QAction(MainWindow)
        self.actionOptimize_Shape.setText(QtGui.QApplication.translate("MainWindow", "Optimize Shape ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOptimize_Shape.setObjectName(_fromUtf8("actionOptimize_Shape"))
        self.actionExport_Shapes = QtGui.QAction(MainWindow)
        self.actionExport_Shapes.setText(QtGui.QApplication.translate("MainWindow", "Export Shapes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_Shapes.setObjectName(_fromUtf8("actionExport_Shapes"))
        self.menuFile.addAction(self.actionLoad_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuExport.addSeparator()
        self.menuExport.addAction(self.actionOptimize_Shape)
        self.menuExport.addAction(self.actionExport_Shapes)
        self.menuView.addAction(self.actionShow_WP_Zero)
        self.menuView.addAction(self.actionShow_path_directions)
        self.menuView.addAction(self.actionShow_disabled_paths)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionAutoscale)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionDelete_G0_paths)
        self.menuTolerances.addAction(self.actionTolerances)
        self.menuTolerances.addSeparator()
        self.menuTolerances.addAction(self.actionScale_all)
        self.menuTolerances.addAction(self.actionRotate_all)
        self.menuTolerances.addSeparator()
        self.menuTolerances.addAction(self.actionMove_WP_zero)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuExport.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTolerances.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.mytabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.mytabWidget.setTabText(self.mytabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Entities", None, QtGui.QApplication.UnicodeUTF8))
        self.mytabWidget.setTabText(self.mytabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Layers", None, QtGui.QApplication.UnicodeUTF8))

from Gui.myCanvasClass import MyGraphicsView
from Gui.myMessageBox import myMessageBox
import dxf2gcode_images_rc
