# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dxf2gcode_pyQt4_ui.ui'
#
# Created: Mon Jun 08 18:52:21 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/DXF2GCODE-001.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.mytabWidget = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mytabWidget.sizePolicy().hasHeightForWidth())
        self.mytabWidget.setSizePolicy(sizePolicy)
        self.mytabWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.mytabWidget.setObjectName(_fromUtf8("mytabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.blocksCollapsePushButton = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blocksCollapsePushButton.sizePolicy().hasHeightForWidth())
        self.blocksCollapsePushButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/collapse-all.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.blocksCollapsePushButton.setIcon(icon1)
        self.blocksCollapsePushButton.setIconSize(QtCore.QSize(24, 24))
        self.blocksCollapsePushButton.setObjectName(_fromUtf8("blocksCollapsePushButton"))
        self.horizontalLayout_5.addWidget(self.blocksCollapsePushButton)
        self.blocksExpandPushButton = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blocksExpandPushButton.sizePolicy().hasHeightForWidth())
        self.blocksExpandPushButton.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/expand-all.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.blocksExpandPushButton.setIcon(icon2)
        self.blocksExpandPushButton.setIconSize(QtCore.QSize(24, 24))
        self.blocksExpandPushButton.setObjectName(_fromUtf8("blocksExpandPushButton"))
        self.horizontalLayout_5.addWidget(self.blocksExpandPushButton)
        spacerItem = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.entitiesTreeView = MyTreeView(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entitiesTreeView.sizePolicy().hasHeightForWidth())
        self.entitiesTreeView.setSizePolicy(sizePolicy)
        self.entitiesTreeView.setObjectName(_fromUtf8("entitiesTreeView"))
        self.verticalLayout_3.addWidget(self.entitiesTreeView)
        self.mytabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setMargin(5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.layersCollapsePushButton = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layersCollapsePushButton.sizePolicy().hasHeightForWidth())
        self.layersCollapsePushButton.setSizePolicy(sizePolicy)
        self.layersCollapsePushButton.setIcon(icon1)
        self.layersCollapsePushButton.setIconSize(QtCore.QSize(24, 24))
        self.layersCollapsePushButton.setObjectName(_fromUtf8("layersCollapsePushButton"))
        self.horizontalLayout_4.addWidget(self.layersCollapsePushButton)
        self.layersExpandPushButton = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layersExpandPushButton.sizePolicy().hasHeightForWidth())
        self.layersExpandPushButton.setSizePolicy(sizePolicy)
        self.layersExpandPushButton.setIcon(icon2)
        self.layersExpandPushButton.setIconSize(QtCore.QSize(24, 24))
        self.layersExpandPushButton.setObjectName(_fromUtf8("layersExpandPushButton"))
        self.horizontalLayout_4.addWidget(self.layersExpandPushButton)
        spacerItem1 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.layersGoUpPushButton = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layersGoUpPushButton.sizePolicy().hasHeightForWidth())
        self.layersGoUpPushButton.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/go-up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.layersGoUpPushButton.setIcon(icon3)
        self.layersGoUpPushButton.setIconSize(QtCore.QSize(24, 24))
        self.layersGoUpPushButton.setObjectName(_fromUtf8("layersGoUpPushButton"))
        self.horizontalLayout_4.addWidget(self.layersGoUpPushButton)
        self.layersGoDownPushButton = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layersGoDownPushButton.sizePolicy().hasHeightForWidth())
        self.layersGoDownPushButton.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/go-down.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.layersGoDownPushButton.setIcon(icon4)
        self.layersGoDownPushButton.setIconSize(QtCore.QSize(24, 24))
        self.layersGoDownPushButton.setObjectName(_fromUtf8("layersGoDownPushButton"))
        self.horizontalLayout_4.addWidget(self.layersGoDownPushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.layersShapesTreeView = MyTreeView(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layersShapesTreeView.sizePolicy().hasHeightForWidth())
        self.layersShapesTreeView.setSizePolicy(sizePolicy)
        self.layersShapesTreeView.setObjectName(_fromUtf8("layersShapesTreeView"))
        self.verticalLayout_5.addWidget(self.layersShapesTreeView)
        self.millSettingsFrame = QtGui.QFrame(self.tab_2)
        self.millSettingsFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.millSettingsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.millSettingsFrame.setLineWidth(0)
        self.millSettingsFrame.setObjectName(_fromUtf8("millSettingsFrame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.millSettingsFrame)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setMargin(2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.toolDiameterComboBox = QtGui.QComboBox(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolDiameterComboBox.sizePolicy().hasHeightForWidth())
        self.toolDiameterComboBox.setSizePolicy(sizePolicy)
        self.toolDiameterComboBox.setMaxVisibleItems(20)
        self.toolDiameterComboBox.setObjectName(_fromUtf8("toolDiameterComboBox"))
        self.horizontalLayout_3.addWidget(self.toolDiameterComboBox)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_11 = QtGui.QLabel(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout.addWidget(self.label_11)
        self.toolDiameterLabel = QtGui.QLabel(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolDiameterLabel.sizePolicy().hasHeightForWidth())
        self.toolDiameterLabel.setSizePolicy(sizePolicy)
        self.toolDiameterLabel.setObjectName(_fromUtf8("toolDiameterLabel"))
        self.horizontalLayout.addWidget(self.toolDiameterLabel)
        self.label_12 = QtGui.QLabel(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout.addWidget(self.label_12)
        self.toolSpeedLabel = QtGui.QLabel(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolSpeedLabel.sizePolicy().hasHeightForWidth())
        self.toolSpeedLabel.setSizePolicy(sizePolicy)
        self.toolSpeedLabel.setObjectName(_fromUtf8("toolSpeedLabel"))
        self.horizontalLayout.addWidget(self.toolSpeedLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_13 = QtGui.QLabel(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_2.addWidget(self.label_13)
        self.startRadiusLabel = QtGui.QLabel(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startRadiusLabel.sizePolicy().hasHeightForWidth())
        self.startRadiusLabel.setSizePolicy(sizePolicy)
        self.startRadiusLabel.setObjectName(_fromUtf8("startRadiusLabel"))
        self.horizontalLayout_2.addWidget(self.startRadiusLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.zInitialMillDepthLineEdit = QtGui.QLineEdit(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zInitialMillDepthLineEdit.sizePolicy().hasHeightForWidth())
        self.zInitialMillDepthLineEdit.setSizePolicy(sizePolicy)
        self.zInitialMillDepthLineEdit.setObjectName(_fromUtf8("zInitialMillDepthLineEdit"))
        self.gridLayout.addWidget(self.zInitialMillDepthLineEdit, 4, 1, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(2)
        self.horizontalLayout_13.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_7 = QtGui.QLabel(self.millSettingsFrame)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_13.addWidget(self.label_7)
        self.unitLabel_8 = QtGui.QLabel(self.millSettingsFrame)
        self.unitLabel_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unitLabel_8.setObjectName(_fromUtf8("unitLabel_8"))
        self.horizontalLayout_13.addWidget(self.unitLabel_8)
        self.gridLayout.addLayout(self.horizontalLayout_13, 7, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(2)
        self.horizontalLayout_12.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_8 = QtGui.QLabel(self.millSettingsFrame)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_12.addWidget(self.label_8)
        self.unitLabel_7 = QtGui.QLabel(self.millSettingsFrame)
        self.unitLabel_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unitLabel_7.setObjectName(_fromUtf8("unitLabel_7"))
        self.horizontalLayout_12.addWidget(self.unitLabel_7)
        self.gridLayout.addLayout(self.horizontalLayout_12, 6, 0, 1, 1)
        self.zInfeedDepthLineEdit = QtGui.QLineEdit(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zInfeedDepthLineEdit.sizePolicy().hasHeightForWidth())
        self.zInfeedDepthLineEdit.setSizePolicy(sizePolicy)
        self.zInfeedDepthLineEdit.setObjectName(_fromUtf8("zInfeedDepthLineEdit"))
        self.gridLayout.addWidget(self.zInfeedDepthLineEdit, 5, 1, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(2)
        self.horizontalLayout_11.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_9 = QtGui.QLabel(self.millSettingsFrame)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_11.addWidget(self.label_9)
        self.unitLabel_6 = QtGui.QLabel(self.millSettingsFrame)
        self.unitLabel_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unitLabel_6.setObjectName(_fromUtf8("unitLabel_6"))
        self.horizontalLayout_11.addWidget(self.unitLabel_6)
        self.gridLayout.addLayout(self.horizontalLayout_11, 5, 0, 1, 1)
        self.zSafetyMarginLineEdit = QtGui.QLineEdit(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zSafetyMarginLineEdit.sizePolicy().hasHeightForWidth())
        self.zSafetyMarginLineEdit.setSizePolicy(sizePolicy)
        self.zSafetyMarginLineEdit.setObjectName(_fromUtf8("zSafetyMarginLineEdit"))
        self.gridLayout.addWidget(self.zSafetyMarginLineEdit, 3, 1, 1, 1)
        self.zFinalMillDepthLineEdit = QtGui.QLineEdit(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zFinalMillDepthLineEdit.sizePolicy().hasHeightForWidth())
        self.zFinalMillDepthLineEdit.setSizePolicy(sizePolicy)
        self.zFinalMillDepthLineEdit.setObjectName(_fromUtf8("zFinalMillDepthLineEdit"))
        self.gridLayout.addWidget(self.zFinalMillDepthLineEdit, 6, 1, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(2)
        self.horizontalLayout_9.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_5 = QtGui.QLabel(self.millSettingsFrame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_9.addWidget(self.label_5)
        self.unitLabel_4 = QtGui.QLabel(self.millSettingsFrame)
        self.unitLabel_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unitLabel_4.setObjectName(_fromUtf8("unitLabel_4"))
        self.horizontalLayout_9.addWidget(self.unitLabel_4)
        self.gridLayout.addLayout(self.horizontalLayout_9, 3, 0, 1, 1)
        self.zRetractionArealLineEdit = QtGui.QLineEdit(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zRetractionArealLineEdit.sizePolicy().hasHeightForWidth())
        self.zRetractionArealLineEdit.setSizePolicy(sizePolicy)
        self.zRetractionArealLineEdit.setObjectName(_fromUtf8("zRetractionArealLineEdit"))
        self.gridLayout.addWidget(self.zRetractionArealLineEdit, 2, 1, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(2)
        self.horizontalLayout_8.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtGui.QLabel(self.millSettingsFrame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.unitLabel_3 = QtGui.QLabel(self.millSettingsFrame)
        self.unitLabel_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unitLabel_3.setObjectName(_fromUtf8("unitLabel_3"))
        self.horizontalLayout_8.addWidget(self.unitLabel_3)
        self.gridLayout.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(2)
        self.horizontalLayout_10.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_14 = QtGui.QLabel(self.millSettingsFrame)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_10.addWidget(self.label_14)
        self.unitLabel_5 = QtGui.QLabel(self.millSettingsFrame)
        self.unitLabel_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unitLabel_5.setObjectName(_fromUtf8("unitLabel_5"))
        self.horizontalLayout_10.addWidget(self.unitLabel_5)
        self.gridLayout.addLayout(self.horizontalLayout_10, 4, 0, 1, 1)
        self.g1FeedZLineEdit = QtGui.QLineEdit(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g1FeedZLineEdit.sizePolicy().hasHeightForWidth())
        self.g1FeedZLineEdit.setSizePolicy(sizePolicy)
        self.g1FeedZLineEdit.setObjectName(_fromUtf8("g1FeedZLineEdit"))
        self.gridLayout.addWidget(self.g1FeedZLineEdit, 8, 1, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.startAtXLabel = QtGui.QLabel(self.millSettingsFrame)
        self.startAtXLabel.setObjectName(_fromUtf8("startAtXLabel"))
        self.horizontalLayout_6.addWidget(self.startAtXLabel)
        self.unitLabel_1 = QtGui.QLabel(self.millSettingsFrame)
        self.unitLabel_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unitLabel_1.setObjectName(_fromUtf8("unitLabel_1"))
        self.horizontalLayout_6.addWidget(self.unitLabel_1)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.startAtYLineEdit = QtGui.QLineEdit(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startAtYLineEdit.sizePolicy().hasHeightForWidth())
        self.startAtYLineEdit.setSizePolicy(sizePolicy)
        self.startAtYLineEdit.setObjectName(_fromUtf8("startAtYLineEdit"))
        self.gridLayout.addWidget(self.startAtYLineEdit, 1, 1, 1, 1)
        self.g1FeedXYLineEdit = QtGui.QLineEdit(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g1FeedXYLineEdit.sizePolicy().hasHeightForWidth())
        self.g1FeedXYLineEdit.setSizePolicy(sizePolicy)
        self.g1FeedXYLineEdit.setObjectName(_fromUtf8("g1FeedXYLineEdit"))
        self.gridLayout.addWidget(self.g1FeedXYLineEdit, 7, 1, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(2)
        self.horizontalLayout_14.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_10 = QtGui.QLabel(self.millSettingsFrame)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_14.addWidget(self.label_10)
        self.unitLabel_9 = QtGui.QLabel(self.millSettingsFrame)
        self.unitLabel_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unitLabel_9.setObjectName(_fromUtf8("unitLabel_9"))
        self.horizontalLayout_14.addWidget(self.unitLabel_9)
        self.gridLayout.addLayout(self.horizontalLayout_14, 8, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(2)
        self.horizontalLayout_7.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.startAtYLabel = QtGui.QLabel(self.millSettingsFrame)
        self.startAtYLabel.setObjectName(_fromUtf8("startAtYLabel"))
        self.horizontalLayout_7.addWidget(self.startAtYLabel)
        self.unitLabel_2 = QtGui.QLabel(self.millSettingsFrame)
        self.unitLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unitLabel_2.setObjectName(_fromUtf8("unitLabel_2"))
        self.horizontalLayout_7.addWidget(self.unitLabel_2)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.startAtXLineEdit = QtGui.QLineEdit(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startAtXLineEdit.sizePolicy().hasHeightForWidth())
        self.startAtXLineEdit.setSizePolicy(sizePolicy)
        self.startAtXLineEdit.setObjectName(_fromUtf8("startAtXLineEdit"))
        self.gridLayout.addWidget(self.startAtXLineEdit, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_5.addWidget(self.millSettingsFrame)
        self.mytabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.MyGraphicsView = MyGraphicsView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MyGraphicsView.sizePolicy().hasHeightForWidth())
        self.MyGraphicsView.setSizePolicy(sizePolicy)
        self.MyGraphicsView.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.MyGraphicsView.setObjectName(_fromUtf8("MyGraphicsView"))
        self.verticalLayout.addWidget(self.splitter)
        self.myMessageBox = myMessageBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.myMessageBox.sizePolicy().hasHeightForWidth())
        self.myMessageBox.setSizePolicy(sizePolicy)
        self.myMessageBox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.myMessageBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.myMessageBox.setObjectName(_fromUtf8("myMessageBox"))
        self.verticalLayout.addWidget(self.myMessageBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuExport = QtGui.QMenu(self.menubar)
        self.menuExport.setEnabled(True)
        self.menuExport.setObjectName(_fromUtf8("menuExport"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuTolerances = QtGui.QMenu(self.menubar)
        self.menuTolerances.setObjectName(_fromUtf8("menuTolerances"))
        self.menuMachine_Type = QtGui.QMenu(self.menuTolerances)
        self.menuMachine_Type.setObjectName(_fromUtf8("menuMachine_Type"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_File = QtGui.QAction(MainWindow)
        self.actionLoad_File.setObjectName(_fromUtf8("actionLoad_File"))
        self.actionExit = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon5)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionShow_WP_Zero = QtGui.QAction(MainWindow)
        self.actionShow_WP_Zero.setCheckable(True)
        self.actionShow_WP_Zero.setChecked(True)
        self.actionShow_WP_Zero.setEnabled(False)
        self.actionShow_WP_Zero.setObjectName(_fromUtf8("actionShow_WP_Zero"))
        self.actionShow_path_directions = QtGui.QAction(MainWindow)
        self.actionShow_path_directions.setCheckable(True)
        self.actionShow_path_directions.setChecked(False)
        self.actionShow_path_directions.setEnabled(False)
        self.actionShow_path_directions.setObjectName(_fromUtf8("actionShow_path_directions"))
        self.actionShow_disabled_paths = QtGui.QAction(MainWindow)
        self.actionShow_disabled_paths.setCheckable(True)
        self.actionShow_disabled_paths.setChecked(False)
        self.actionShow_disabled_paths.setEnabled(False)
        self.actionShow_disabled_paths.setObjectName(_fromUtf8("actionShow_disabled_paths"))
        self.actionAutoscale = QtGui.QAction(MainWindow)
        self.actionAutoscale.setEnabled(False)
        self.actionAutoscale.setObjectName(_fromUtf8("actionAutoscale"))
        self.actionDelete_G0_paths = QtGui.QAction(MainWindow)
        self.actionDelete_G0_paths.setEnabled(False)
        self.actionDelete_G0_paths.setObjectName(_fromUtf8("actionDelete_G0_paths"))
        self.actionTolerances = QtGui.QAction(MainWindow)
        self.actionTolerances.setObjectName(_fromUtf8("actionTolerances"))
        self.actionScale_all = QtGui.QAction(MainWindow)
        self.actionScale_all.setEnabled(False)
        self.actionScale_all.setObjectName(_fromUtf8("actionScale_all"))
        self.actionRotate_all = QtGui.QAction(MainWindow)
        self.actionRotate_all.setEnabled(False)
        self.actionRotate_all.setObjectName(_fromUtf8("actionRotate_all"))
        self.actionMove_WP_zero = QtGui.QAction(MainWindow)
        self.actionMove_WP_zero.setEnabled(False)
        self.actionMove_WP_zero.setObjectName(_fromUtf8("actionMove_WP_zero"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionOptimize_Shape = QtGui.QAction(MainWindow)
        self.actionOptimize_Shape.setObjectName(_fromUtf8("actionOptimize_Shape"))
        self.actionExport_Shapes = QtGui.QAction(MainWindow)
        self.actionExport_Shapes.setObjectName(_fromUtf8("actionExport_Shapes"))
        self.actionOptimize_and_Export_shapes = QtGui.QAction(MainWindow)
        self.actionOptimize_and_Export_shapes.setObjectName(_fromUtf8("actionOptimize_and_Export_shapes"))
        self.actionLive_update_export_route = QtGui.QAction(MainWindow)
        self.actionLive_update_export_route.setCheckable(True)
        self.actionLive_update_export_route.setEnabled(False)
        self.actionLive_update_export_route.setObjectName(_fromUtf8("actionLive_update_export_route"))
        self.actionReload_File = QtGui.QAction(MainWindow)
        self.actionReload_File.setObjectName(_fromUtf8("actionReload_File"))
        self.actionSplit_Edges = QtGui.QAction(MainWindow)
        self.actionSplit_Edges.setCheckable(True)
        self.actionSplit_Edges.setObjectName(_fromUtf8("actionSplit_Edges"))
        self.actionAutomatic_Cutter_Compensation = QtGui.QAction(MainWindow)
        self.actionAutomatic_Cutter_Compensation.setCheckable(True)
        self.actionAutomatic_Cutter_Compensation.setEnabled(False)
        self.actionAutomatic_Cutter_Compensation.setObjectName(_fromUtf8("actionAutomatic_Cutter_Compensation"))
        self.actionMilling = QtGui.QAction(MainWindow)
        self.actionMilling.setCheckable(True)
        self.actionMilling.setObjectName(_fromUtf8("actionMilling"))
        self.actionDrag_Knife = QtGui.QAction(MainWindow)
        self.actionDrag_Knife.setCheckable(True)
        self.actionDrag_Knife.setObjectName(_fromUtf8("actionDrag_Knife"))
        self.actionLathe = QtGui.QAction(MainWindow)
        self.actionLathe.setCheckable(True)
        self.actionLathe.setObjectName(_fromUtf8("actionLathe"))
        self.menuFile.addAction(self.actionLoad_File)
        self.menuFile.addAction(self.actionReload_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuExport.addSeparator()
        self.menuExport.addAction(self.actionOptimize_Shape)
        self.menuExport.addAction(self.actionExport_Shapes)
        self.menuExport.addAction(self.actionOptimize_and_Export_shapes)
        self.menuView.addAction(self.actionShow_WP_Zero)
        self.menuView.addAction(self.actionShow_path_directions)
        self.menuView.addAction(self.actionShow_disabled_paths)
        self.menuView.addAction(self.actionLive_update_export_route)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionAutoscale)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionDelete_G0_paths)
        self.menuMachine_Type.addAction(self.actionMilling)
        self.menuMachine_Type.addAction(self.actionLathe)
        self.menuMachine_Type.addAction(self.actionDrag_Knife)
        self.menuTolerances.addAction(self.actionTolerances)
        self.menuTolerances.addSeparator()
        self.menuTolerances.addAction(self.actionScale_all)
        self.menuTolerances.addAction(self.actionRotate_all)
        self.menuTolerances.addSeparator()
        self.menuTolerances.addAction(self.actionMove_WP_zero)
        self.menuTolerances.addSeparator()
        self.menuTolerances.addAction(self.actionSplit_Edges)
        self.menuTolerances.addAction(self.actionAutomatic_Cutter_Compensation)
        self.menuTolerances.addAction(self.menuMachine_Type.menuAction())
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuExport.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTolerances.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.mytabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.layersCollapsePushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.layersShapesTreeView.collapseAll)
        QtCore.QObject.connect(self.layersExpandPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.layersShapesTreeView.expandAll)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "DXF2GCODE", None))
        self.blocksCollapsePushButton.setToolTip(_translate("MainWindow", "Collapse all items", None))
        self.blocksExpandPushButton.setToolTip(_translate("MainWindow", "Expand all items", None))
        self.mytabWidget.setTabText(self.mytabWidget.indexOf(self.tab), _translate("MainWindow", "Entities", None))
        self.layersCollapsePushButton.setToolTip(_translate("MainWindow", "Collapse all items", None))
        self.layersExpandPushButton.setToolTip(_translate("MainWindow", "Expand all items", None))
        self.layersGoUpPushButton.setToolTip(_translate("MainWindow", "Move-up the selected shape/layer", None))
        self.layersGoDownPushButton.setToolTip(_translate("MainWindow", "Move-down the selected shape/layer", None))
        self.label_11.setText(_translate("MainWindow", "⌀", None))
        self.toolDiameterLabel.setText(_translate("MainWindow", "[mm]", None))
        self.label_12.setText(_translate("MainWindow", "/ speed ", None))
        self.toolSpeedLabel.setText(_translate("MainWindow", "[rpm]", None))
        self.label_13.setText(_translate("MainWindow", "start rad. (comp) ", None))
        self.startRadiusLabel.setText(_translate("MainWindow", "[mm]", None))
        self.zInitialMillDepthLineEdit.setToolTip(_translate("MainWindow", "Milling will start at Z = \"Worpiece top Z\" - \"Z infeed depth\"", None))
        self.label_7.setText(_translate("MainWindow", "Feed rate XY", None))
        self.unitLabel_8.setText(_translate("MainWindow", "[mm/min]", None))
        self.label_8.setText(_translate("MainWindow", "Z Final mill depth", None))
        self.unitLabel_7.setText(_translate("MainWindow", "[mm]", None))
        self.label_9.setText(_translate("MainWindow", "Z Infeed depth", None))
        self.unitLabel_6.setText(_translate("MainWindow", "[mm]", None))
        self.label_5.setText(_translate("MainWindow", "Z Safety margin", None))
        self.unitLabel_4.setText(_translate("MainWindow", "[mm]", None))
        self.label_6.setText(_translate("MainWindow", "Z Retraction area", None))
        self.unitLabel_3.setText(_translate("MainWindow", "[mm]", None))
        self.label_14.setText(_translate("MainWindow", "Z Workpiece top", None))
        self.unitLabel_5.setText(_translate("MainWindow", "[mm]", None))
        self.startAtXLabel.setText(_translate("MainWindow", "Start X", None))
        self.unitLabel_1.setText(_translate("MainWindow", "[mm]", None))
        self.label_10.setText(_translate("MainWindow", "Feed rate Z", None))
        self.unitLabel_9.setText(_translate("MainWindow", "[mm/min]", None))
        self.startAtYLabel.setText(_translate("MainWindow", "Start Y", None))
        self.unitLabel_2.setText(_translate("MainWindow", "[mm]", None))
        self.mytabWidget.setTabText(self.mytabWidget.indexOf(self.tab_2), _translate("MainWindow", "Layers", None))
        self.MyGraphicsView.setToolTip(_translate("MainWindow", "Graphic Area for drawing\n"
"", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuExport.setStatusTip(_translate("MainWindow", "Export the current project to G-Code", None))
        self.menuExport.setTitle(_translate("MainWindow", "Export", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuTolerances.setTitle(_translate("MainWindow", "Options", None))
        self.menuMachine_Type.setTitle(_translate("MainWindow", "Machine Type", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionLoad_File.setText(_translate("MainWindow", "Load File", None))
        self.actionLoad_File.setStatusTip(_translate("MainWindow", "Load DXF or other supportet document", None))
        self.actionLoad_File.setShortcut(_translate("MainWindow", "Ctrl+L", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionExit.setStatusTip(_translate("MainWindow", "Exit DXF2GCODE and close window", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionShow_WP_Zero.setText(_translate("MainWindow", "Show WP zero", None))
        self.actionShow_WP_Zero.setStatusTip(_translate("MainWindow", "Show the Workpiece Zero symbol in the plot.", None))
        self.actionShow_path_directions.setText(_translate("MainWindow", "Show path directions", None))
        self.actionShow_path_directions.setStatusTip(_translate("MainWindow", "Always shows the path direction in the plot (not only while selected)", None))
        self.actionShow_disabled_paths.setText(_translate("MainWindow", "Show disabled paths", None))
        self.actionAutoscale.setText(_translate("MainWindow", "Autoscale", None))
        self.actionDelete_G0_paths.setText(_translate("MainWindow", "Delete G0 paths", None))
        self.actionTolerances.setText(_translate("MainWindow", "Tolerances", None))
        self.actionScale_all.setText(_translate("MainWindow", "Scale all", None))
        self.actionRotate_all.setText(_translate("MainWindow", "Rotate all", None))
        self.actionMove_WP_zero.setText(_translate("MainWindow", "Move WP zero", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionOptimize_Shape.setText(_translate("MainWindow", "Optimize Paths ", None))
        self.actionOptimize_Shape.setShortcut(_translate("MainWindow", "Ctrl+Shift+O", None))
        self.actionExport_Shapes.setText(_translate("MainWindow", "Export Shapes", None))
        self.actionExport_Shapes.setShortcut(_translate("MainWindow", "Ctrl+Shift+E", None))
        self.actionOptimize_and_Export_shapes.setText(_translate("MainWindow", "Optimize and Export shapes", None))
        self.actionOptimize_and_Export_shapes.setShortcut(_translate("MainWindow", "Ctrl+E", None))
        self.actionLive_update_export_route.setText(_translate("MainWindow", "Live update export route", None))
        self.actionReload_File.setText(_translate("MainWindow", "Reload File", None))
        self.actionReload_File.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.actionSplit_Edges.setText(_translate("MainWindow", "Split Edges", None))
        self.actionSplit_Edges.setStatusTip(_translate("MainWindow", "Split edges, e.g. can be used for compensation (G41/G42) in combination with EMC", None))
        self.actionAutomatic_Cutter_Compensation.setText(_translate("MainWindow", "Automatic Cutter Compensation", None))
        self.actionMilling.setText(_translate("MainWindow", "Milling", None))
        self.actionDrag_Knife.setText(_translate("MainWindow", "Drag Knife", None))
        self.actionLathe.setText(_translate("MainWindow", "Lathe", None))

from Gui.myCanvasClass import MyGraphicsView
from Gui.myTreeView import MyTreeView
from Gui.myMessageBox import myMessageBox
import dxf2gcode_images_rc
