# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dxf2gcode.ui'
#
# Created: Sat Dec 19 12:05:29 2015
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 601)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/DXF2GCODE-001.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.mytabWidget = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mytabWidget.sizePolicy().hasHeightForWidth())
        self.mytabWidget.setSizePolicy(sizePolicy)
        self.mytabWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.mytabWidget.setAutoFillBackground(False)
        self.mytabWidget.setObjectName(_fromUtf8("mytabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.blocksCollapsePushButton = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blocksCollapsePushButton.sizePolicy().hasHeightForWidth())
        self.blocksCollapsePushButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/collapse-all.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.blocksCollapsePushButton.setIcon(icon1)
        self.blocksCollapsePushButton.setIconSize(QtCore.QSize(24, 24))
        self.blocksCollapsePushButton.setObjectName(_fromUtf8("blocksCollapsePushButton"))
        self.horizontalLayout_5.addWidget(self.blocksCollapsePushButton)
        self.blocksExpandPushButton = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blocksExpandPushButton.sizePolicy().hasHeightForWidth())
        self.blocksExpandPushButton.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/expand-all.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.blocksExpandPushButton.setIcon(icon2)
        self.blocksExpandPushButton.setIconSize(QtCore.QSize(24, 24))
        self.blocksExpandPushButton.setObjectName(_fromUtf8("blocksExpandPushButton"))
        self.horizontalLayout_5.addWidget(self.blocksExpandPushButton)
        spacerItem = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.entitiesTreeView = TreeView(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entitiesTreeView.sizePolicy().hasHeightForWidth())
        self.entitiesTreeView.setSizePolicy(sizePolicy)
        self.entitiesTreeView.setObjectName(_fromUtf8("entitiesTreeView"))
        self.verticalLayout_3.addWidget(self.entitiesTreeView)
        self.mytabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setMargin(5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.layersCollapsePushButton = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layersCollapsePushButton.sizePolicy().hasHeightForWidth())
        self.layersCollapsePushButton.setSizePolicy(sizePolicy)
        self.layersCollapsePushButton.setIcon(icon1)
        self.layersCollapsePushButton.setIconSize(QtCore.QSize(24, 24))
        self.layersCollapsePushButton.setObjectName(_fromUtf8("layersCollapsePushButton"))
        self.horizontalLayout_4.addWidget(self.layersCollapsePushButton)
        self.layersExpandPushButton = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layersExpandPushButton.sizePolicy().hasHeightForWidth())
        self.layersExpandPushButton.setSizePolicy(sizePolicy)
        self.layersExpandPushButton.setIcon(icon2)
        self.layersExpandPushButton.setIconSize(QtCore.QSize(24, 24))
        self.layersExpandPushButton.setObjectName(_fromUtf8("layersExpandPushButton"))
        self.horizontalLayout_4.addWidget(self.layersExpandPushButton)
        spacerItem1 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.layersGoUpPushButton = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layersGoUpPushButton.sizePolicy().hasHeightForWidth())
        self.layersGoUpPushButton.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/go-up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.layersGoUpPushButton.setIcon(icon3)
        self.layersGoUpPushButton.setIconSize(QtCore.QSize(24, 24))
        self.layersGoUpPushButton.setObjectName(_fromUtf8("layersGoUpPushButton"))
        self.horizontalLayout_4.addWidget(self.layersGoUpPushButton)
        self.layersGoDownPushButton = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layersGoDownPushButton.sizePolicy().hasHeightForWidth())
        self.layersGoDownPushButton.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/go-down.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.layersGoDownPushButton.setIcon(icon4)
        self.layersGoDownPushButton.setIconSize(QtCore.QSize(24, 24))
        self.layersGoDownPushButton.setObjectName(_fromUtf8("layersGoDownPushButton"))
        self.horizontalLayout_4.addWidget(self.layersGoDownPushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.layersShapesTreeView = TreeView(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layersShapesTreeView.sizePolicy().hasHeightForWidth())
        self.layersShapesTreeView.setSizePolicy(sizePolicy)
        self.layersShapesTreeView.setObjectName(_fromUtf8("layersShapesTreeView"))
        self.verticalLayout_5.addWidget(self.layersShapesTreeView)
        self.millSettingsFrame = QtGui.QFrame(self.tab_2)
        self.millSettingsFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.millSettingsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.millSettingsFrame.setLineWidth(0)
        self.millSettingsFrame.setObjectName(_fromUtf8("millSettingsFrame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.millSettingsFrame)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setMargin(2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.toolDiameterComboBox = QtGui.QComboBox(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolDiameterComboBox.sizePolicy().hasHeightForWidth())
        self.toolDiameterComboBox.setSizePolicy(sizePolicy)
        self.toolDiameterComboBox.setMaxVisibleItems(20)
        self.toolDiameterComboBox.setObjectName(_fromUtf8("toolDiameterComboBox"))
        self.horizontalLayout_3.addWidget(self.toolDiameterComboBox)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_11 = QtGui.QLabel(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout.addWidget(self.label_11)
        self.toolDiameterLabel = QtGui.QLabel(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolDiameterLabel.sizePolicy().hasHeightForWidth())
        self.toolDiameterLabel.setSizePolicy(sizePolicy)
        self.toolDiameterLabel.setText(_fromUtf8("[mm]"))
        self.toolDiameterLabel.setObjectName(_fromUtf8("toolDiameterLabel"))
        self.horizontalLayout.addWidget(self.toolDiameterLabel)
        self.label_12 = QtGui.QLabel(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout.addWidget(self.label_12)
        self.toolSpeedLabel = QtGui.QLabel(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolSpeedLabel.sizePolicy().hasHeightForWidth())
        self.toolSpeedLabel.setSizePolicy(sizePolicy)
        self.toolSpeedLabel.setText(_fromUtf8("[rpm]"))
        self.toolSpeedLabel.setObjectName(_fromUtf8("toolSpeedLabel"))
        self.horizontalLayout.addWidget(self.toolSpeedLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_13 = QtGui.QLabel(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_2.addWidget(self.label_13)
        self.startRadiusLabel = QtGui.QLabel(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startRadiusLabel.sizePolicy().hasHeightForWidth())
        self.startRadiusLabel.setSizePolicy(sizePolicy)
        self.startRadiusLabel.setText(_fromUtf8("[mm]"))
        self.startRadiusLabel.setObjectName(_fromUtf8("startRadiusLabel"))
        self.horizontalLayout_2.addWidget(self.startRadiusLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.startAtYLineEdit = QtGui.QLineEdit(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startAtYLineEdit.sizePolicy().hasHeightForWidth())
        self.startAtYLineEdit.setSizePolicy(sizePolicy)
        self.startAtYLineEdit.setObjectName(_fromUtf8("startAtYLineEdit"))
        self.gridLayout.addWidget(self.startAtYLineEdit, 5, 1, 1, 1)
        self.zInitialMillDepthLineEdit = QtGui.QLineEdit(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zInitialMillDepthLineEdit.sizePolicy().hasHeightForWidth())
        self.zInitialMillDepthLineEdit.setSizePolicy(sizePolicy)
        self.zInitialMillDepthLineEdit.setObjectName(_fromUtf8("zInitialMillDepthLineEdit"))
        self.gridLayout.addWidget(self.zInitialMillDepthLineEdit, 9, 1, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(2)
        self.horizontalLayout_13.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_7 = QtGui.QLabel(self.millSettingsFrame)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_13.addWidget(self.label_7)
        self.unitLabel_8 = QtGui.QLabel(self.millSettingsFrame)
        self.unitLabel_8.setText(_fromUtf8("[mm/min]"))
        self.unitLabel_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unitLabel_8.setObjectName(_fromUtf8("unitLabel_8"))
        self.horizontalLayout_13.addWidget(self.unitLabel_8)
        self.gridLayout.addLayout(self.horizontalLayout_13, 12, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(2)
        self.horizontalLayout_12.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_8 = QtGui.QLabel(self.millSettingsFrame)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_12.addWidget(self.label_8)
        self.unitLabel_7 = QtGui.QLabel(self.millSettingsFrame)
        self.unitLabel_7.setText(_fromUtf8("[mm]"))
        self.unitLabel_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unitLabel_7.setObjectName(_fromUtf8("unitLabel_7"))
        self.horizontalLayout_12.addWidget(self.unitLabel_7)
        self.gridLayout.addLayout(self.horizontalLayout_12, 11, 0, 1, 1)
        self.zInfeedDepthLineEdit = QtGui.QLineEdit(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zInfeedDepthLineEdit.sizePolicy().hasHeightForWidth())
        self.zInfeedDepthLineEdit.setSizePolicy(sizePolicy)
        self.zInfeedDepthLineEdit.setObjectName(_fromUtf8("zInfeedDepthLineEdit"))
        self.gridLayout.addWidget(self.zInfeedDepthLineEdit, 10, 1, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(2)
        self.horizontalLayout_11.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_9 = QtGui.QLabel(self.millSettingsFrame)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_11.addWidget(self.label_9)
        self.unitLabel_6 = QtGui.QLabel(self.millSettingsFrame)
        self.unitLabel_6.setText(_fromUtf8("[mm]"))
        self.unitLabel_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unitLabel_6.setObjectName(_fromUtf8("unitLabel_6"))
        self.horizontalLayout_11.addWidget(self.unitLabel_6)
        self.gridLayout.addLayout(self.horizontalLayout_11, 10, 0, 1, 1)
        self.zSafetyMarginLineEdit = QtGui.QLineEdit(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zSafetyMarginLineEdit.sizePolicy().hasHeightForWidth())
        self.zSafetyMarginLineEdit.setSizePolicy(sizePolicy)
        self.zSafetyMarginLineEdit.setObjectName(_fromUtf8("zSafetyMarginLineEdit"))
        self.gridLayout.addWidget(self.zSafetyMarginLineEdit, 8, 1, 1, 1)
        self.zFinalMillDepthLineEdit = QtGui.QLineEdit(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zFinalMillDepthLineEdit.sizePolicy().hasHeightForWidth())
        self.zFinalMillDepthLineEdit.setSizePolicy(sizePolicy)
        self.zFinalMillDepthLineEdit.setObjectName(_fromUtf8("zFinalMillDepthLineEdit"))
        self.gridLayout.addWidget(self.zFinalMillDepthLineEdit, 11, 1, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(2)
        self.horizontalLayout_9.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_5 = QtGui.QLabel(self.millSettingsFrame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_9.addWidget(self.label_5)
        self.unitLabel_4 = QtGui.QLabel(self.millSettingsFrame)
        self.unitLabel_4.setText(_fromUtf8("[mm]"))
        self.unitLabel_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unitLabel_4.setObjectName(_fromUtf8("unitLabel_4"))
        self.horizontalLayout_9.addWidget(self.unitLabel_4)
        self.gridLayout.addLayout(self.horizontalLayout_9, 8, 0, 1, 1)
        self.zRetractionArealLineEdit = QtGui.QLineEdit(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zRetractionArealLineEdit.sizePolicy().hasHeightForWidth())
        self.zRetractionArealLineEdit.setSizePolicy(sizePolicy)
        self.zRetractionArealLineEdit.setObjectName(_fromUtf8("zRetractionArealLineEdit"))
        self.gridLayout.addWidget(self.zRetractionArealLineEdit, 6, 1, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(2)
        self.horizontalLayout_8.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtGui.QLabel(self.millSettingsFrame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.unitLabel_3 = QtGui.QLabel(self.millSettingsFrame)
        self.unitLabel_3.setText(_fromUtf8("[mm]"))
        self.unitLabel_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unitLabel_3.setObjectName(_fromUtf8("unitLabel_3"))
        self.horizontalLayout_8.addWidget(self.unitLabel_3)
        self.gridLayout.addLayout(self.horizontalLayout_8, 6, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(2)
        self.horizontalLayout_10.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_14 = QtGui.QLabel(self.millSettingsFrame)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_10.addWidget(self.label_14)
        self.unitLabel_5 = QtGui.QLabel(self.millSettingsFrame)
        self.unitLabel_5.setText(_fromUtf8("[mm]"))
        self.unitLabel_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unitLabel_5.setObjectName(_fromUtf8("unitLabel_5"))
        self.horizontalLayout_10.addWidget(self.unitLabel_5)
        self.gridLayout.addLayout(self.horizontalLayout_10, 9, 0, 1, 1)
        self.g1FeedZLineEdit = QtGui.QLineEdit(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g1FeedZLineEdit.sizePolicy().hasHeightForWidth())
        self.g1FeedZLineEdit.setSizePolicy(sizePolicy)
        self.g1FeedZLineEdit.setObjectName(_fromUtf8("g1FeedZLineEdit"))
        self.gridLayout.addWidget(self.g1FeedZLineEdit, 13, 1, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.startAtXLabel = QtGui.QLabel(self.millSettingsFrame)
        self.startAtXLabel.setObjectName(_fromUtf8("startAtXLabel"))
        self.horizontalLayout_6.addWidget(self.startAtXLabel)
        self.unitLabel_1 = QtGui.QLabel(self.millSettingsFrame)
        self.unitLabel_1.setText(_fromUtf8("[mm]"))
        self.unitLabel_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unitLabel_1.setObjectName(_fromUtf8("unitLabel_1"))
        self.horizontalLayout_6.addWidget(self.unitLabel_1)
        self.gridLayout.addLayout(self.horizontalLayout_6, 4, 0, 1, 1)
        self.g1FeedXYLineEdit = QtGui.QLineEdit(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g1FeedXYLineEdit.sizePolicy().hasHeightForWidth())
        self.g1FeedXYLineEdit.setSizePolicy(sizePolicy)
        self.g1FeedXYLineEdit.setObjectName(_fromUtf8("g1FeedXYLineEdit"))
        self.gridLayout.addWidget(self.g1FeedXYLineEdit, 12, 1, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(2)
        self.horizontalLayout_14.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_10 = QtGui.QLabel(self.millSettingsFrame)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_14.addWidget(self.label_10)
        self.unitLabel_9 = QtGui.QLabel(self.millSettingsFrame)
        self.unitLabel_9.setText(_fromUtf8("[mm/min]"))
        self.unitLabel_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unitLabel_9.setObjectName(_fromUtf8("unitLabel_9"))
        self.horizontalLayout_14.addWidget(self.unitLabel_9)
        self.gridLayout.addLayout(self.horizontalLayout_14, 13, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(2)
        self.horizontalLayout_7.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.startAtYLabel = QtGui.QLabel(self.millSettingsFrame)
        self.startAtYLabel.setObjectName(_fromUtf8("startAtYLabel"))
        self.horizontalLayout_7.addWidget(self.startAtYLabel)
        self.unitLabel_2 = QtGui.QLabel(self.millSettingsFrame)
        self.unitLabel_2.setText(_fromUtf8("[mm]"))
        self.unitLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unitLabel_2.setObjectName(_fromUtf8("unitLabel_2"))
        self.horizontalLayout_7.addWidget(self.unitLabel_2)
        self.gridLayout.addLayout(self.horizontalLayout_7, 5, 0, 1, 1)
        self.startAtXLineEdit = QtGui.QLineEdit(self.millSettingsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startAtXLineEdit.sizePolicy().hasHeightForWidth())
        self.startAtXLineEdit.setSizePolicy(sizePolicy)
        self.startAtXLineEdit.setObjectName(_fromUtf8("startAtXLineEdit"))
        self.gridLayout.addWidget(self.startAtXLineEdit, 4, 1, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_15 = QtGui.QLabel(self.millSettingsFrame)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_15.addWidget(self.label_15)
        self.unitLabel_10 = QtGui.QLabel(self.millSettingsFrame)
        self.unitLabel_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.unitLabel_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unitLabel_10.setObjectName(_fromUtf8("unitLabel_10"))
        self.horizontalLayout_15.addWidget(self.unitLabel_10)
        self.gridLayout.addLayout(self.horizontalLayout_15, 2, 0, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_16 = QtGui.QLabel(self.millSettingsFrame)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_16.addWidget(self.label_16)
        self.unitLabel_11 = QtGui.QLabel(self.millSettingsFrame)
        self.unitLabel_11.setObjectName(_fromUtf8("unitLabel_11"))
        self.horizontalLayout_16.addWidget(self.unitLabel_11)
        self.gridLayout.addLayout(self.horizontalLayout_16, 0, 0, 1, 1)
        self.laserPowerLineEdit = QtGui.QLineEdit(self.millSettingsFrame)
        self.laserPowerLineEdit.setObjectName(_fromUtf8("laserPowerLineEdit"))
        self.gridLayout.addWidget(self.laserPowerLineEdit, 2, 1, 1, 1)
        self.laserPulsesPerMMLineEdit = QtGui.QLineEdit(self.millSettingsFrame)
        self.laserPulsesPerMMLineEdit.setObjectName(_fromUtf8("laserPulsesPerMMLineEdit"))
        self.gridLayout.addWidget(self.laserPulsesPerMMLineEdit, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_5.addWidget(self.millSettingsFrame)
        self.mytabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.canvas = Canvas(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvas.sizePolicy().hasHeightForWidth())
        self.canvas.setSizePolicy(sizePolicy)
        self.canvas.setMinimumSize(QtCore.QSize(200, 200))
        self.canvas.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.canvas.setObjectName(_fromUtf8("canvas"))
        self.verticalLayout.addWidget(self.splitter)
        self.messageBox = MessageBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messageBox.sizePolicy().hasHeightForWidth())
        self.messageBox.setSizePolicy(sizePolicy)
        self.messageBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.messageBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.messageBox.setObjectName(_fromUtf8("messageBox"))
        self.verticalLayout.addWidget(self.messageBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuExport = QtGui.QMenu(self.menubar)
        self.menuExport.setEnabled(True)
        self.menuExport.setObjectName(_fromUtf8("menuExport"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuTolerances = QtGui.QMenu(self.menubar)
        self.menuTolerances.setObjectName(_fromUtf8("menuTolerances"))
        self.menuMachine_Type = QtGui.QMenu(self.menuTolerances)
        self.menuMachine_Type.setObjectName(_fromUtf8("menuMachine_Type"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionClose = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon5)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionShowPathDirections = QtGui.QAction(MainWindow)
        self.actionShowPathDirections.setCheckable(True)
        self.actionShowPathDirections.setChecked(False)
        self.actionShowPathDirections.setEnabled(False)
        self.actionShowPathDirections.setObjectName(_fromUtf8("actionShowPathDirections"))
        self.actionShowDisabledPaths = QtGui.QAction(MainWindow)
        self.actionShowDisabledPaths.setCheckable(True)
        self.actionShowDisabledPaths.setChecked(False)
        self.actionShowDisabledPaths.setEnabled(False)
        self.actionShowDisabledPaths.setObjectName(_fromUtf8("actionShowDisabledPaths"))
        self.actionAutoscale = QtGui.QAction(MainWindow)
        self.actionAutoscale.setEnabled(False)
        self.actionAutoscale.setObjectName(_fromUtf8("actionAutoscale"))
        self.actionDeleteG0Paths = QtGui.QAction(MainWindow)
        self.actionDeleteG0Paths.setEnabled(False)
        self.actionDeleteG0Paths.setObjectName(_fromUtf8("actionDeleteG0Paths"))
        self.actionTolerances = QtGui.QAction(MainWindow)
        self.actionTolerances.setObjectName(_fromUtf8("actionTolerances"))
        self.actionScaleAll = QtGui.QAction(MainWindow)
        self.actionScaleAll.setEnabled(False)
        self.actionScaleAll.setObjectName(_fromUtf8("actionScaleAll"))
        self.actionRotateAll = QtGui.QAction(MainWindow)
        self.actionRotateAll.setEnabled(False)
        self.actionRotateAll.setObjectName(_fromUtf8("actionRotateAll"))
        self.actionMoveWorkpieceZero = QtGui.QAction(MainWindow)
        self.actionMoveWorkpieceZero.setEnabled(False)
        self.actionMoveWorkpieceZero.setObjectName(_fromUtf8("actionMoveWorkpieceZero"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionOptimizePaths = QtGui.QAction(MainWindow)
        self.actionOptimizePaths.setEnabled(False)
        self.actionOptimizePaths.setObjectName(_fromUtf8("actionOptimizePaths"))
        self.actionExportShapes = QtGui.QAction(MainWindow)
        self.actionExportShapes.setEnabled(False)
        self.actionExportShapes.setObjectName(_fromUtf8("actionExportShapes"))
        self.actionOptimizeAndExportShapes = QtGui.QAction(MainWindow)
        self.actionOptimizeAndExportShapes.setEnabled(False)
        self.actionOptimizeAndExportShapes.setObjectName(_fromUtf8("actionOptimizeAndExportShapes"))
        self.actionLiveUpdateExportRoute = QtGui.QAction(MainWindow)
        self.actionLiveUpdateExportRoute.setCheckable(True)
        self.actionLiveUpdateExportRoute.setEnabled(False)
        self.actionLiveUpdateExportRoute.setObjectName(_fromUtf8("actionLiveUpdateExportRoute"))
        self.actionReload = QtGui.QAction(MainWindow)
        self.actionReload.setEnabled(False)
        self.actionReload.setObjectName(_fromUtf8("actionReload"))
        self.actionSplitLineSegments = QtGui.QAction(MainWindow)
        self.actionSplitLineSegments.setCheckable(True)
        self.actionSplitLineSegments.setObjectName(_fromUtf8("actionSplitLineSegments"))
        self.actionAutomaticCutterCompensation = QtGui.QAction(MainWindow)
        self.actionAutomaticCutterCompensation.setCheckable(True)
        self.actionAutomaticCutterCompensation.setEnabled(False)
        self.actionAutomaticCutterCompensation.setObjectName(_fromUtf8("actionAutomaticCutterCompensation"))
        self.actionMilling = QtGui.QAction(MainWindow)
        self.actionMilling.setCheckable(True)
        self.actionMilling.setObjectName(_fromUtf8("actionMilling"))
        self.actionDragKnife = QtGui.QAction(MainWindow)
        self.actionDragKnife.setCheckable(True)
        self.actionDragKnife.setObjectName(_fromUtf8("actionDragKnife"))
        self.actionLathe = QtGui.QAction(MainWindow)
        self.actionLathe.setCheckable(True)
        self.actionLathe.setObjectName(_fromUtf8("actionLathe"))
        self.actionTopView = QtGui.QAction(MainWindow)
        self.actionTopView.setEnabled(False)
        self.actionTopView.setObjectName(_fromUtf8("actionTopView"))
        self.actionIsometricView = QtGui.QAction(MainWindow)
        self.actionIsometricView.setEnabled(False)
        self.actionIsometricView.setObjectName(_fromUtf8("actionIsometricView"))
        self.actionSaveProjectAs = QtGui.QAction(MainWindow)
        self.actionSaveProjectAs.setEnabled(False)
        self.actionSaveProjectAs.setObjectName(_fromUtf8("actionSaveProjectAs"))
        self.action2x_laser = QtGui.QAction(MainWindow)
        self.action2x_laser.setCheckable(True)
        self.action2x_laser.setObjectName(_fromUtf8("action2x_laser"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionReload)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSaveProjectAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuExport.addAction(self.actionOptimizePaths)
        self.menuExport.addAction(self.actionExportShapes)
        self.menuExport.addAction(self.actionOptimizeAndExportShapes)
        self.menuView.addAction(self.actionShowPathDirections)
        self.menuView.addAction(self.actionShowDisabledPaths)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionLiveUpdateExportRoute)
        self.menuView.addAction(self.actionDeleteG0Paths)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionAutoscale)
        self.menuView.addAction(self.actionTopView)
        self.menuView.addAction(self.actionIsometricView)
        self.menuMachine_Type.addAction(self.actionMilling)
        self.menuMachine_Type.addAction(self.actionLathe)
        self.menuMachine_Type.addAction(self.actionDragKnife)
        self.menuMachine_Type.addAction(self.action2x_laser)
        self.menuTolerances.addAction(self.actionTolerances)
        self.menuTolerances.addSeparator()
        self.menuTolerances.addAction(self.actionScaleAll)
        self.menuTolerances.addAction(self.actionRotateAll)
        self.menuTolerances.addSeparator()
        self.menuTolerances.addAction(self.actionMoveWorkpieceZero)
        self.menuTolerances.addSeparator()
        self.menuTolerances.addAction(self.actionSplitLineSegments)
        self.menuTolerances.addAction(self.actionAutomaticCutterCompensation)
        self.menuTolerances.addAction(self.menuMachine_Type.menuAction())
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuExport.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTolerances.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.mytabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.layersCollapsePushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.layersShapesTreeView.collapseAll)
        QtCore.QObject.connect(self.layersExpandPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.layersShapesTreeView.expandAll)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.mytabWidget, self.entitiesTreeView)
        MainWindow.setTabOrder(self.entitiesTreeView, self.blocksCollapsePushButton)
        MainWindow.setTabOrder(self.blocksCollapsePushButton, self.blocksExpandPushButton)
        MainWindow.setTabOrder(self.blocksExpandPushButton, self.canvas)
        MainWindow.setTabOrder(self.canvas, self.messageBox)
        MainWindow.setTabOrder(self.messageBox, self.layersShapesTreeView)
        MainWindow.setTabOrder(self.layersShapesTreeView, self.layersCollapsePushButton)
        MainWindow.setTabOrder(self.layersCollapsePushButton, self.layersExpandPushButton)
        MainWindow.setTabOrder(self.layersExpandPushButton, self.layersGoUpPushButton)
        MainWindow.setTabOrder(self.layersGoUpPushButton, self.layersGoDownPushButton)
        MainWindow.setTabOrder(self.layersGoDownPushButton, self.toolDiameterComboBox)
        MainWindow.setTabOrder(self.toolDiameterComboBox, self.startAtXLineEdit)
        MainWindow.setTabOrder(self.startAtXLineEdit, self.startAtYLineEdit)
        MainWindow.setTabOrder(self.startAtYLineEdit, self.zRetractionArealLineEdit)
        MainWindow.setTabOrder(self.zRetractionArealLineEdit, self.zSafetyMarginLineEdit)
        MainWindow.setTabOrder(self.zSafetyMarginLineEdit, self.zInitialMillDepthLineEdit)
        MainWindow.setTabOrder(self.zInitialMillDepthLineEdit, self.zInfeedDepthLineEdit)
        MainWindow.setTabOrder(self.zInfeedDepthLineEdit, self.zFinalMillDepthLineEdit)
        MainWindow.setTabOrder(self.zFinalMillDepthLineEdit, self.g1FeedXYLineEdit)
        MainWindow.setTabOrder(self.g1FeedXYLineEdit, self.g1FeedZLineEdit)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "DXF2GCODE", None, QtGui.QApplication.UnicodeUTF8))
        self.blocksCollapsePushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Collapse all items", None, QtGui.QApplication.UnicodeUTF8))
        self.blocksExpandPushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Expand all items", None, QtGui.QApplication.UnicodeUTF8))
        self.mytabWidget.setTabText(self.mytabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Entities", None, QtGui.QApplication.UnicodeUTF8))
        self.layersCollapsePushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Collapse all items", None, QtGui.QApplication.UnicodeUTF8))
        self.layersExpandPushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Expand all items", None, QtGui.QApplication.UnicodeUTF8))
        self.layersGoUpPushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Move-up the selected shape/layer", None, QtGui.QApplication.UnicodeUTF8))
        self.layersGoDownPushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Move-down the selected shape/layer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "⌀", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "/ speed ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "start rad. (comp) ", None, QtGui.QApplication.UnicodeUTF8))
        self.zInitialMillDepthLineEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "Milling will start at Z = \"Workpiece top Z\" - \"Z infeed depth\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Feed rate XY", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Z Final mill depth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Z Infeed depth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Z Safety margin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Z Retraction area", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Z Workpiece top", None, QtGui.QApplication.UnicodeUTF8))
        self.startAtXLabel.setText(QtGui.QApplication.translate("MainWindow", "Start X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Feed rate Z", None, QtGui.QApplication.UnicodeUTF8))
        self.startAtYLabel.setText(QtGui.QApplication.translate("MainWindow", "Start Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Laser Power", None, QtGui.QApplication.UnicodeUTF8))
        self.unitLabel_10.setText(QtGui.QApplication.translate("MainWindow", "[%]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Laser Pulses Per mm", None, QtGui.QApplication.UnicodeUTF8))
        self.unitLabel_11.setText(QtGui.QApplication.translate("MainWindow", "[ppmm]", None, QtGui.QApplication.UnicodeUTF8))
        self.mytabWidget.setTabText(self.mytabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Layers", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExport.setStatusTip(QtGui.QApplication.translate("MainWindow", "Export the current project to G-Code", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExport.setTitle(QtGui.QApplication.translate("MainWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTolerances.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMachine_Type.setTitle(QtGui.QApplication.translate("MainWindow", "Machine Type", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setStatusTip(QtGui.QApplication.translate("MainWindow", "Load DXF or other supported document", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setStatusTip(QtGui.QApplication.translate("MainWindow", "Exit DXF2GCODE and close window", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowPathDirections.setText(QtGui.QApplication.translate("MainWindow", "Show Path Directions", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowPathDirections.setStatusTip(QtGui.QApplication.translate("MainWindow", "Always shows the path direction in the plot (not only while selected)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowDisabledPaths.setText(QtGui.QApplication.translate("MainWindow", "Show Disabled Paths", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoscale.setText(QtGui.QApplication.translate("MainWindow", "Autoscale", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoscale.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+V, A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeleteG0Paths.setText(QtGui.QApplication.translate("MainWindow", "Delete G0 Paths", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTolerances.setText(QtGui.QApplication.translate("MainWindow", "Tolerances", None, QtGui.QApplication.UnicodeUTF8))
        self.actionScaleAll.setText(QtGui.QApplication.translate("MainWindow", "Scale All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRotateAll.setText(QtGui.QApplication.translate("MainWindow", "Rotate All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMoveWorkpieceZero.setText(QtGui.QApplication.translate("MainWindow", "Move Workpiece Zero", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOptimizePaths.setText(QtGui.QApplication.translate("MainWindow", "Optimize Paths", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOptimizePaths.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportShapes.setText(QtGui.QApplication.translate("MainWindow", "Export Shapes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportShapes.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOptimizeAndExportShapes.setText(QtGui.QApplication.translate("MainWindow", "Optimize and Export Shapes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOptimizeAndExportShapes.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLiveUpdateExportRoute.setText(QtGui.QApplication.translate("MainWindow", "Live Update Export Route", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReload.setText(QtGui.QApplication.translate("MainWindow", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReload.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSplitLineSegments.setText(QtGui.QApplication.translate("MainWindow", "Split Line Segments", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSplitLineSegments.setStatusTip(QtGui.QApplication.translate("MainWindow", "Split line segments, e.g. can be used for compensation (G41/G42) in combination with EMC", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutomaticCutterCompensation.setText(QtGui.QApplication.translate("MainWindow", "Automatic Cutter Compensation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMilling.setText(QtGui.QApplication.translate("MainWindow", "Milling", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDragKnife.setText(QtGui.QApplication.translate("MainWindow", "Drag Knife", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLathe.setText(QtGui.QApplication.translate("MainWindow", "Lathe", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTopView.setText(QtGui.QApplication.translate("MainWindow", "Top View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTopView.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+V, T", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIsometricView.setText(QtGui.QApplication.translate("MainWindow", "Isometric View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIsometricView.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+V, I", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveProjectAs.setText(QtGui.QApplication.translate("MainWindow", "Save Project As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveProjectAs.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action2x_laser.setText(QtGui.QApplication.translate("MainWindow", "2x_laser", None, QtGui.QApplication.UnicodeUTF8))

from gui.canvas import Canvas
from gui.treeview import TreeView
from gui.messagebox import MessageBox
import dxf2gcode_images4_rc
